##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
##########

##########
url: "https://cornellhonorsproject.github.io"
baseurl: "/draft01"
source-code: "https://github.com/cornellhonorsproject/draft01"

##########
# SITE SETTINGS
title: "War on the Boulevard"
tagline: "Visual Politics and DIY Aesthetics (1980-1992)"
description: "A digital collection of political punk posters and flyers from the Reagan and Bush administrations."
keywords: "punk; reagan; bush; political posters; archives; DIY"
author: "Catherine Frank"

##########
# COLLECTION SETTINGS
# Your CSV file in the _data folder must be named 'posters.csv'
metadata: "posters"

##########
# ORGANIZATION SETTINGS
organization-name: "Cornell Music by CF"
organization-link: "https://music.cornell.edu/"
organization-logo-banner: false
organization-logo-nav: false

##########
# ROBOTS EXCLUDE
# noindex: true 

##########
# BUILD SETTINGS 
# These paths help the site find your CSS and JS folders
lib-assets: "/assets/lib"
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
sass:
  style: compressed
